### Creation d'un compte medecin
POST http://localhost:8081/api/v1/auth/inscription
Content-Type: application/json

{
  "email": "fred@hopital-medecin.fr",
  "password": "fred"
}

> {%
    client.global.set("fred_token", response.headers.valueOf("Authorization"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### Connexion d'un compte medecin
POST http://localhost:8081/api/v1/auth/connexion
Content-Type: application/json

{
  "email": "fred@hopital-medecin.fr",
  "password": "fred"
}

> {%
    client.global.set("fred_token", response.headers.valueOf("Authorization"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Recuperation de la liste des utilisateurs en tant que medecin
GET http://localhost:8081/api/v1/auth/utilisateurs
Authorization: {{fred_token}}

### Recuperation de la liste des utilisateurs par role => les patients
GET http://localhost:8081/api/v1/auth/utilisateurs/type?role=PATIENT
Authorization: {{fred_token}}

### Recuperation de la liste des utilisateurs par role => les medecins
GET http://localhost:8081/api/v1/auth/utilisateurs/type?role=MEDECIN
Authorization: {{fred_token}}



### Recuperation du compte medecin avec un token valide
GET http://localhost:8081/api/v1/auth/utilisateurs/fred@hopital-medecin.fr
Authorization: {{fred_token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Recuperation du compte medecin avec un token valide
GET http://localhost:8081/api/v1/auth/inscription/fred@hopital-medecin.fr
Authorization: Bearer invalide

#> {%
#    client.test("Request executed successfully", function() {
#        client.assert(response.status === 200, "Response status is not 200");
#    });
#%}



### Création d'un compte patient
POST http://localhost:8081/api/v1/auth/inscription
Content-Type: application/json

{
  "email": "yohan@univ-orleans.fr",
  "password": "pass"
}

> {%
    client.global.set("yoh_token", response.headers.valueOf("Authorization"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### Connexion d'un compte patient valide
POST http://localhost:8081/api/v1/auth/connexion
Content-Type: application/json

{
  "email": "yohan@univ-orleans.fr",
  "password": "pass"
}

> {%
    client.global.set("yoh_token", response.headers.valueOf("Authorization"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Recuperation du compte patient par son propriétaire avec un token valide
GET http://localhost:8081/api/v1/auth/utilisateurs/yohan@univ-orleans.fr
Authorization: {{yoh_token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Récupération d'un compte d'un autre => non autorisé
GET http://localhost:8081/api/v1/auth/utilisateurs/fred@hopital-medecin.fr
Authorization: {{yoh_token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 403, "Response status is not 403");
    });
%}


### Modification du mot de passe d'un compte valide
PATCH http://localhost:8081/api/v1/auth/utilisateurs/mot-de-passe
Authorization: {{fred_token}}
Content-Type: application/json

{
  "email": "fred@hopital-medecin.fr",
  "password": "newpass"
}

### Connexion d'un compte avec le nouveau mot de passe
POST http://localhost:8081/api/v1/auth/connexion
Content-Type: application/json

{
  "email": "fred@hopital-medecin.fr",
  "password": "newpass"
}

> {%
    client.global.set("yoh_token", response.headers.valueOf("Authorization"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Suppression d'un compte medecin par son propriétaire
GET http://localhost:8081/api/v1/auth/utilisateurs/fred@hopital-medecin.fr
Authorization: {{fred_token}}

### Suppression d'un compte medecin par son propriétaire
DELETE http://localhost:8081/api/v1/auth/utilisateurs/fred@hopital-medecin.fr
Authorization: {{fred_token}}

