POST http://localhost:8081/api/v1/auth/inscription
Content-Type: application/json

{
  "email": "fred22@univ-orleans.fr",
  "password": "fred"
}

> {%
    client.global.set("fred_token", response.headers.valueOf("Authorization"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

###
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "login": "fred14@univ-orleans.fr",
  "password": "fred"
}

> {%
    client.global.set("yoh_token", response.headers.valueOf("Authorization"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###

GET http://localhost:8081/api/v1/auth/inscription/fred@univ-orleans.fr
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiZnJlZEB1bml2LW9ybGVhbnMuZnIiLCJleHAiOjE2NzgwNzA3NjAsImlhdCI6MTY3ODAzNDc2MCwic2NvcGUiOiIifQ.fdiIVIeiQESE3LVuR1BFHmDBB5J5inS-GWmePwQbkx3cY2Lgd0RITCVHt8tgLew6lottQXyzo3k3MIvDS4Kl5sj4_U1HLH1LxyFMnTYL1m2UV7M4KwfOULjxyRHt5CvpHfOzEPDidWUxAs0geHdecz-Qz1qa24ZKlAHzBhr_lN2ZXxppfgFtYOJoq6XGc0Y3tWz_4zgKSJZzXe0BHSzMMKQmWhVNWsztMd-r5Mo6U2_g0kSTXPtY4UGiMI5Y9UyKtsAZoNc1NBVs-FRO2w8czDwkT8QN3buvIODz32GBjFjOaWxiD9nZS7880_xyp6jDie_sUglMSBsUv-xVngGMWQ


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


###
POST http://localhost:8081/api/v1/auth/inscription
Content-Type: application/json

{
  "email": "yohand@univ-orleans.fr",
  "password": "pass"
}

> {%
    client.global.set("fred_token", response.headers.valueOf("Authorization"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

###
GET http://localhost:8081/api/v1/auth/inscription/fred
Authorization: {{yoh_token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 403, "Response status is not 403");
    });
%}


###
GET http://localhost:8081/api/v1/auth/inscription/yohan.boichut@univ-orleans.fr
Authorization: {{yoh_token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


###
GET http://localhost:8081/api/v1/auth/inscription/yohan.boichut@univ-orleans.fr
Authorization: {{yoh_token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


