POST http://localhost:8081/api/v1/authent/inscription
Content-Type: application/json

{
  "email": "fred@univ-orleans.fr",
  "password": "fred"
}

> {%
    client.global.set("fred_token", response.headers.valueOf("Authorization"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

###
POST http://localhost:8081/api/v1/authent/login
Content-Type: application/json

{
  "login": "yohan.boichut@gmail.com",
  "password": "pass"
}

> {%
    client.global.set("yoh_token", response.headers.valueOf("Authorization"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###

GET http://localhost:8081/api/v1/authent/inscription/fred@univ-orleans.fr
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiZnJlZEB1bml2LW9ybGVhbnMuZnIiLCJleHAiOjE2NzgwMDk4NzMsImlhdCI6MTY3Nzk3Mzg3Mywic2NvcGUiOiIifQ.DtDyP-Tl36-1fBRbXmPxBl4wUTFAJxXQYXdT5J1CSYwmN9iwYetSIuxir7v-HMux5bwo9YC7DdRWOa8RCtX3386rJNbfSDTLJEMqzrjzRvZUGkC6c4CPO2C3hGpPZu0CItU530O3LwPPFTxqLSZUeDq7xooQQPC7pMLWXu-Ly21J3Xkb0TIqbyNIu1mxbFNhQ28iwMGxNJvvQ5x9AdsSuDzCRhAax4Yjwy7l8MICNAZKwpuY4r_yxTjbpXEGokBExiqD_4yeA8d1Gh7L2HFpsrH_6YtW_C69is2bKtqMuuTemGWb8HShTKWsdIZGWUhpswWfWdE7_7PZJ9C6z1WBnA


> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
GET http://localhost:8081/api/v1/authent/inscription/fred
Authorization: {{yoh_token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 403, "Response status is not 403");
    });
%}

###
GET http://localhost:8081/api/v1/authent/inscription/yohan.boichut@gmail.com
Authorization: {{yoh_token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


