
############################################
#             Utilisateurs                 #
############################################

POST http://localhost:8080/api/auth/inscription
Content-Type: application/json

{
  "email": "fred1@hopital-secretaire.fr",
  "password": "fred"
}

> {%
    client.global.set("token_confirm_secretaire", response.headers.valueOf("Token-Confirmation"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
});
%}

### Connexion d'un compte secretaire
POST http://localhost:8080/api/auth/connexion
Content-Type: application/json

{
  "email": "fred1@hopital-secretaire.fr",
  "password": "fred"
}

> {%
      client.global.set("secretaire_token", response.headers.valueOf("Authorization"));
      client.test("Request executed successfully", function() {
      client.assert(response.status === 200, "Response status is not 200");
      });
%}

### get panier utilisateur###
GET http://localhost:8080/gestionnaire/utilisateurs/2/panier
Authorization: {{secretaire_token}}


############################################
#                  Produit                 #
############################################


POST http://localhost:8080/gestionnaire/produits
Authorization: {{secretaire_token}}
Content-Type: application/json

{
    "nomProduitMedical": "Spasfon",
    "prixProduitMedical": 3.35,
    "descriptionProduitMedical": "Maux de ventre"
}


### Ajouter un produit dans un panier###

POST http://localhost:8080/gestionnaire/utilisateurs/2/panier?idProduit=5&quantite=5
Authorization: {{secretaire_token}}


### Ajout produit dans le catalogue fournisseur ###
POST http://localhost:8080/gestionnaire/fournisseurs/2/catalogue?idProduit=5
Authorization: {{secretaire_token}}

### Supprimer un produit dans un panier###

DELETE http://localhost:8080/gestionnaire/utilisateurs/2/panier/6
Authorization: {{secretaire_token}}

### supprimer un produit ###

DELETE http://localhost:8080/gestionnaire/produits/{idProduit}
Authorization: {{secretaire_token}}

### supprimer un produit d'un catalogue fournisseur###

DELETE http://localhost:8080/gestionnaire/fournisseurs/{idFournisseur}/catalogue/{idProduit}
Authorization: {{secretaire_token}}

### get stock produit ###

GET http://localhost:8080/gestionnaire/produits/4/stock
Authorization: {{secretaire_token}}

### modifier un produit son prix , son nom ou sa descritpion ou les trois en memes temps ###
PATCH http://localhost:8080/gestionnaire/produits/5
Authorization: {{secretaire_token}}
Content-Type: application/json

{
  "nomProduitMedical": "Spasfona"
}



############################################
#                  Fournisseurs            #
############################################

### Ajout Fournisseur###

POST http://localhost:8080/gestionnaire/fournisseurs
Authorization: {{secretaire_token}}
Content-Type: application/json

    {
    "nomFournisseur": "HindIndustry",
    "adresseFournisseur": "Chez Hind ",
    "telephoneFournisseur": "061516511"
    }

### modifier un fournisseur###

PATCH http://localhost:8080/gestionnaire/fournisseurs/2
Authorization: {{secretaire_token}}
Content-Type: application/json

{
  "nomFournisseur": "AzizIndustry",
  "telephoneFournisseur": "0613261147"
}

### supprimer un fournisseur###

DELETE http://localhost:8080/gestionnaire/fournisseurs/2
Authorization: {{secretaire_token}}

### get fournisseur by id###

GET http://localhost:8080/gestionnaire/fournisseurs/2
Authorization: {{secretaire_token}}

### get catalogue fournisseur###

GET http://localhost:8080/gestionnaire/fournisseurs/4/catalogue
Authorization: {{secretaire_token}}


############################################
#                  Commandes               #
############################################


### passer commande###
POST http://localhost:8080/gestionnaire/utilisateurs/2/passerCommande
Authorization: {{secretaire_token}}

### Annuler commande###

DELETE http://localhost:8080/gestionnaire/commandes/2
Authorization: {{secretaire_token}}

### get commande by id###

GET http://localhost:8080/gestionnaire/commandes/1
Authorization: {{secretaire_token}}


### Get panier d une commande ###

GET http://localhost:8080/gestionnaire/commandes/{idCommande}/panier
Authorization: {{secretaire_token}}

### Get all commandes ###

GET http://localhost:8080/gestionnaire/commandes
Authorization: {{secretaire_token}}
