### creation d'une facture
POST http://localhost:8080/api/facture/v1/new-bill
Content-Type: application/json

{
  "dateFature": "2023-03-17T22:02:15.806Z",
  "nomPatient": "rachida.el-ouariachi@etu.univ-orleans.fr",
  "produits": [
    {
      "nom": "calpol",
      "marque": "parcetamol",
      "quantite": 5
    },
    {
      "nom": "doliprane",
      "marque": "parcetamol",
      "quantite": 5
    }
  ]
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### récupération de la facture
GET http://localhost:8080/api/facture/bill/6417a347cc33dbd37d280d38
Accept: application/json



### récupération toutes les factures
GET http://localhost:8080/api/facture/bill
Accept: application/json

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Test de l'envoi de la facture par mail
GET http://localhost:8080/api/facture/v1/send/patients?idFacture=6419b1b58d08b399c2607130&idPatients=rachida.el-ouariachi@etu.univ-orleans.fr
