##################################################
#################AUTHENTIFICATION#################
##################################################

### Inscription d'un compte secretaire
POST http://localhost:8081/api/v1/auth/inscription
Content-Type: application/json

{
  "email": "fred@hopital-secretaire.fr",
  "password": "fred"
}

> {%
    client.global.set("token_confirm_secretaire", response.headers.valueOf("Token-Confirmation"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}
### Confirmation du compte secretaire
GET http://localhost:8081/api/v1/auth/confirmation-compte?token={{token_confirm_secretaire}}
### Connexion d'un compte secretaire
POST http://localhost:8081/api/v1/auth/connexion
Content-Type: application/json

{
  "email": "fred@hopital-secretaire.fr",
  "password": "fred"
}

> {%
    client.global.set("secretaire_token", response.headers.valueOf("Authorization"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Inscription d'un compte médecin
POST http://localhost:8081/api/v1/auth/inscription
Content-Type: application/json

{
  "email": "fred@hopital-medecin.fr",
  "password": "fred"
}

> {%
    client.global.set("token_confirm_medecin", response.headers.valueOf("Token-Confirmation"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}
### Confirmation du compte médecin
GET http://localhost:8081/api/v1/auth/confirmation-compte?token={{token_confirm_medecin}}
### Connexion d'un compte médecin
POST http://localhost:8081/api/v1/auth/connexion
Content-Type: application/json

{
  "email": "fred@hopital-medecin.fr",
  "password": "fred"
}

> {%
    client.global.set("medecin_token", response.headers.valueOf("Authorization"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Inscription d'un compte patient
POST http://localhost:8081/api/v1/auth/inscription
Content-Type: application/json

{
  "email": "fred@univ-orleans.fr",
  "password": "fred"
}

> {%
    client.global.set("token_confirm_patient", response.headers.valueOf("Token-Confirmation"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}
### Confirmation du compte patient
GET http://localhost:8081/api/v1/auth/confirmation-compte?token={{token_confirm_patient}}
### Connexion d'un compte patient
POST http://localhost:8081/api/v1/auth/connexion
Content-Type: application/json

{
  "email": "fred@univ-orleans.fr",
  "password": "fred"
}

> {%
    client.global.set("patient_token", response.headers.valueOf("Authorization"));
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###################################################
################SERVICE RDVPATIENTS################
###################################################

### Cette requete permet de créer un medecin // SECRETAIRE
POST http://localhost:8083/api/v1/rdvpatients/medecin
Authorization: {{secretaire_token}}
Content-Type: application/json

{
  "prenom": "Hind",
  "nom": "HACHEMI",
  "email": "hind.hachemi@hopital-medecin.fr"
}

### Cette requete permet de créer un patient // SECRETAIRE
POST http://localhost:8083/api/v1/rdvpatients/patient
Authorization: {{secretaire_token}}
Content-Type: application/json

{
  "prenom": "Aaron",
  "nom": "BROSSEAU",
  "email": "brosseau.aaron@gmail.com",
  "numSecu": "15",
  "numTel": "0123456789",
  "dateNaissance": "14-02-2000",
  "genre": "Homme"
}

### Cette requete permet d'ajouter les antécédents d'un patient à son profil // MEDECIN
PATCH http://localhost:8083/api/v1/rdvpatients/personnel/modif/patient/15/antecedents
Authorization: {{secretaire_token}}
Content-Type: application/json

{
  "antecedents": "Fragile"
}

### Cette requete permet de voir les données d'un patient // MEDECIN OU PATIENT OU SECRETAIRE
GET http://localhost:8083/api/v1/rdvpatients/patient/15
Authorization: {{secretaire_token}}

### Cette requete permet d'assigner un medecin à un patient
PATCH http://localhost:8083/api/v1/rdvpatients/personnel/modif/patient/15/medecintraitant
Authorization: {{secretaire_token}}
Content-Type: application/json

{
  "prenom": "Hind",
  "nom": "HACHEMI"
}

### Cette requete permet de prendre un rendez vous pour un patient
POST http://localhost:8083/api/v1/rdvpatients/consultation
Authorization: {{secretaire_token}}
Content-Type: application/json

{
  "dateRDV": "28-08-2022",
  "heureRDV": "18H30",
  "motif": "Mal de crâne",
  "type": "SOINS_DIVERS",
  "ordonnance": "Doliprane 2 fois par jour"
}

### Cette requete permet à un médecin de confirmer la consultation
PATCH http://localhost:8083/api/v1/rdvpatients/consultation/1/confirmer
Authorization: {{secretaire_token}}


### Cette requete permet d'ajouter un compte rendu a une consultation
PATCH http://localhost:8083/api/v1/rdvpatients/consultation/1/compterendu
Authorization: {{secretaire_token}}
Content-Type: application/json

{
  "compteRendu" : "Patient fievreux",
  "listeProduitsMedicaux" : ["Doliprane:1","Pansement:2"]
}

### Cette requete permet de voir les consultations d'un medecin
GET http://localhost:8083/api/v1/rdvpatients/medecin/9/consultations
Authorization: {{secretaire_token}}

### Cette requete permet de demander d'annuler un RDV pour un patient
DELETE http://localhost:8083/api/v1/rdvpatients/consultation/1/annulation
Authorization: {{secretaire_token}}

Content-Type: application/json