### Ajout utilisateur###
POST http://localhost:8084/api/v1/gestionnaire/utilisateurs
Content-Type: application/json

{
    "nomUtilisateur": "Hackime",
    "prenomUtilisateur": "BOUJDI",
    "emailUtilisateur": "tktmonreuf"
}

### Ajout Produit####

POST http://localhost:8084/api/v1/gestionnaire/produitsMedical
Content-Type: application/json

{
    "nomProduitMedical": "Eferalgan",
    "prixProduitMedical": 17.0,
    "descriptionProduitMedical": "Maux de tete"
}

### Ajout Fournisseur###

POST http://localhost:8084/api/v1/gestionnaire/fournisseurs
Content-Type: application/json

    {
    "nomFournisseur": "HindIndustry",
    "adresseFournisseur": "Chez Hind ",
    "telephoneFournisseur": "061516511"
    }

### Ajout produit dans le catalogue fournisseur ###
POST http://localhost:8084/api/v1/gestionnaire/fournisseurs/2/catalogue?idProduit=3

### Ajouter un produit dans un panier###

POST http://localhost:8084/api/v1/gestionnaire/utilisateurs/2/panier?idProduit=3&quantite=12


### passer commande###
POST http://localhost:8084/api/v1/gestionnaire/utilisateurs/2/passerCommande

### Supprimer un produit dans un panier###

DELETE http://localhost:8084/api/v1/gestionnaire/utilisateurs/2/panier/6

### Annuler commande###

DELETE http://localhost:8080/gestionnaire/commandes/2

### supprimer un fournisseur###

DELETE http://localhost:8084/api/v1/gestionnaire/fournisseurs/2

### supprimer un produit###

DELETE http://localhost:8084/api/v1/gestionnaire/produitsMedical/{idProduit}

### supprimer un produit d'un catalogue fournisseur###

DELETE http://localhost:8084/api/v1/gestionnaire/fournisseurs/{idFournisseur}/catalogue/{idProduit}

### modifier un fournisseur###

PATCH http://localhost:8084/api/v1/gestionnaire/fournisseurs/2
Content-Type: application/json-patch+json

{
    "op": "replace",
    "path": "/0",
    "value": "0713261147"
}


### modifier un produit###
//PATC


### get commande by id###

GET http://localhost:8084/api/v1/gestionnaire/commandes/1

### get panier utilisateur###
GET http://localhost:8084/api/v1/gestionnaire/utilisateurs/2/panier

### get fournisseur by id###

GET http://localhost:8084/api/v1/gestionnaire/fournisseurs/2

### get stock produit###

GET http://localhost:8084/api/v1/gestionnaire/produitsMedical/3/stock

### get catalogue fournisseur###

GET http://localhost:8084/api/v1/gestionnaire/fournisseurs/4/catalogue

### Get panier d une commande ###

GET http://localhost:8080/gestionnaire/commandes/{idCommande}/panier

### Get all commandes ###

GET http://localhost:8080/gestionnaire/commandes
