### Ajout utilisateur###
POST http://localhost:8084/api/v1/gestionnaire/utilisateurs
Content-Type: application/json

{
  "nomUtilisateur": "utilisateur",
  "prenomUtilisateur": "prenom1",
  "emailUtilisateur": "email10"
}

#### Ajout Produit####

POST http://localhost:8084/api/v1/gestionnaire/produitsMedical
Content-Type: application/json

{
  "nomProduitMedical": "produit2",
  "prixProduitMedical": 10.0,
  "descriptionProduitMedical": "gagagagagaga"
}

### Ajout Fournisseur###

POST http://localhost:8084/api/v1/gestionnaire/fournisseurs
Content-Type: application/json

{
  "nomFournisseur": "fournisseur5",
  "adresseFournisseur": "adresse1",
  "telephoneFournisseur": "061516511"
}

### Ajout produit dans le catalogue fournisseur ###
POST http://localhost:8084/api/v1/gestionnaire/fournisseurs/14/catalogue?idProduit=3
Content-Type: application/json



### Ajouter un produit dans un panier###

POST http://localhost:8084/api/v1/gestionnaire/utilisateurs/20/panier?idProduit=29&quantite=5
Content-Type: application/json


#### passer commande###

POST http://localhost:8084/api/v1/gestionnaire/utilisateurs/20/passerCommande

### Supprimer un produit dans un panier###

DELETE http://localhost:8084/api/v1/gestionnaire/utilisateurs/20/panier/13

### Annuler commande###
DELETE http://localhost:8084/api/v1/gestionnaire/commandes/4

### supprimer un fournisseur###

DELETE http://localhost:8084/api/v1/gestionnaire/fournisseurs/6

### supprimer un produit d'un catalogue fournisseur
DELETE http://localhost:8084/api/v1/gestionnaire/fournisseurs/14/produits/3

### modifier un fournisseur
PATCH http://localhost:8084/api/v1/gestionnaire/fournisseurs/12
##marche pas

#### modifier un produit###

PATCH http://localhost:8084/api/v1/gestionnaire/produitMedical/{idProduit}
#marche pas

### get commande by id###

GET http://localhost:8084/api/v1/gestionnaire/commandes/6


### get fournisseur by id###

GET http://localhost:8084/api/v1/gestionnaire/fournisseurs/12

### get stock produit###

GET http://localhost:8084/api/v1/gestionnaire/produitsMedical/13/stock

### get catalogue fournisseur###
GET http://localhost:8084/api/v1/gestionnaire/fournisseurs/14/catalogue


#### Get produits d un panier ###
GET http://localhost:8084/api/v1/gestionnaire/utilisateurs/13/panier

### Get all commandes
GET http://localhost:8084/api/v1/gestionnaire/commandes

