### Endpoint for sending an email notification
POST http://localhost:8080//api/v1/notification/email
Content-Type: application/json

{
  "destinataire": "noreply.hopital@gmail.com",
  "objet": "Test Email Microservice",
  "contenu": "Bonjour, ceci est un email de test. Le microservice de messagerie fonctionne."
}

### Endpoint for sending an email notification
POST http://localhost:8080/api/v1/notification/email
Content-Type: application/json

{
  "destinataire": "rachida.el-ouariachi@etu.univ-orleans.fr",
  "objet": "Test du service de messagerie du micro-service Hopital (M2 MIAGE)",
  "contenu": "Bonjour, ceci est un e-mail de test pour vérifier que notre service de messagerie fonctionne correctement.\n\nCordialement, \n\nDes étudiants en M2 MIAGE de l'Université d'Orléans."

}

