### Cette requete permet de creer un medecin (que pr la secretaire) ###
POST http://localhost:8080/rdvpatients/medecin/nouveau
Content-Type: application/json

{
  "prenom_uti": "Hind",
  "nom_uti": "HACHEMI",
  "email_uti": "hind.hachemi@etu.univ-orleans.fr"
}

### Cette requete permet de creer un patient (que pr la secretaire) ###
POST http://localhost:8080/rdvpatients/patient/nouveau
Content-Type: application/json

{
  "prenom_uti": "Hind",
  "nom_uti": "HACHEMI",
  "email_uti": "hind.hachemi@etu.univ-orleans.fr",
  "numsecu_pat": "15",
  "numtel_pat": "15",
  "datenais_pat": "22-01-2001",
  "genre_pat": "Homme"
}

### Cette requete permet d'ajouter les antécédents d'un patient à son profil
PATCH http://localhost:8080/rdvpatients/personnel/modif/patent/15/antecedents
Content-Type: application/json

{
  "antecedents_pat": "Allergique au gluten"
}

### Cette requete permet d'assigner un medecin à un patient
PATCH http://localhost:8080/rdvpatients/personnel/modif/patient/15/medecintraitant
Content-Type: application/json

{ "prenom_uti": "Eric",
  "nom_uti": "DAVID"
}

### Cette requete permet à un médecin de confirmer la consultation
PATCH http://localhost:8080/rdvpatients/consultation/7/confirmer

### Cette requete permet de voir les consultations d'un medecin
GET http://localhost:8080/rdvpatients/medecin/2/consultations

### Cette requete permet d'ajouter un compte rendu a une consultation
PATCH http://localhost:8080/rdvpatients/consultation/7/compterendu
Content-Type: application/json

{ "cr_cons" : "Rhume nécessitant du repos" }


### Cette requete permet de prendre un rendez vous pour un patient
PATCH http://localhost:8080/rdvpatients/consultation/nouveau
Content-Type: application/json

{
  "motif_cons": "Douleur au dos",
  "type_cons": "VISITE_MEDICALE",
  "ordo_cons": " Doliprane 2 fois par jour",
  "heureRDV": "14H20",
  "dateRDV": "15-07-2022"
}
### Cette requete permet de demander d'annuler un RDV pour un patient
POST http://localhost:8080/rdvpatients/consultation/5/demandeannulation
Content-Type: application/json
{
  "motif" : "Imprevu"
}

